# Generated by Django 5.1.5 on 2025-02-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnaval', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCarnaval',
            new_name='Event',
        ),
    ]
