# Generated by Django 5.1.5 on 2025-02-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnaval', '0002_rename_eventcarnaval_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
